export const Utilisateurs = [
    {
        id: 1,
        nom: 'Doe',
        prenom: 'John',
        cin: 'ABC123',
        numTel: '123456789',
        password: 'password123',
        email: 'john.doe@example.com',
        address: '123 Main Street',
        date_naissance: '1990-01-01',
    },
    {
        id: 2,
        nom: 'Smith',
        prenom: 'Jane',
        cin: 'XYZ789',
        numTel: '987654321',
        password: 'pass123',
        email: 'jane.smith@example.com',
        address: '456 Oak Avenue',
        date_naissance: '1985-05-15',
    },
    {
        id: 3,
        nom: 'Johnson',
        prenom: 'Robert',
        cin: 'DEF456',
        numTel: '5555555555',
        password: 'robertpass',
        email: 'robert.johnson@example.com',
        address: '789 Maple Street',
        date_naissance: '1982-08-20',
    },
    {
        id: 4,
        nom: 'Williams',
        prenom: 'Emily',
        cin: 'GHI789',
        numTel: '3332221111',
        password: 'emilypass',
        email: 'emily.williams@example.com',
        address: '101 Elm Street',
        date_naissance: '1998-04-10',
    },
    {
        id: 5,
        nom: 'Brown',
        prenom: 'Michael',
        cin: 'JKL123',
        numTel: '7778889999',
        password: 'michaelpass',
        email: 'michael.brown@example.com',
        address: '202 Cedar Avenue',
        date_naissance: '1977-12-05',
    },
    {
        id: 6,
        nom: 'Davis',
        prenom: 'Olivia',
        cin: 'MNO456',
        numTel: '4443332222',
        password: 'oliviapass',
        email: 'olivia.davis@example.com',
        address: '303 Pine Street',
        date_naissance: '1993-09-25',
    },
    {
        id: 7,
        nom: 'Martinez',
        prenom: 'Daniel',
        cin: 'PQR789',
        numTel: '9998887777',
        password: 'danielpass',
        email: 'daniel.martinez@example.com',
        address: '404 Birch Avenue',
        date_naissance: '1988-06-15',
    },
    {
        id: 8,
        nom: 'Anderson',
        prenom: 'Sophia',
        cin: 'STU123',
        numTel: '6665554444',
        password: 'sophiapass',
        email: 'sophia.anderson@example.com',
        address: '505 Oak Street',
        date_naissance: '1996-02-28',
    },
    {
        id: 9,
        nom: 'Taylor',
        prenom: 'Ethan',
        cin: 'VWX456',
        numTel: '1112223333',
        password: 'ethanpass',
        email: 'ethan.taylor@example.com',
        address: '606 Maple Avenue',
        date_naissance: '1980-11-12',
    },
    {
        id: 10,
        nom: 'Moore',
        prenom: 'Ava',
        cin: 'YZA789',
        numTel: '8889990000',
        password: 'avapass',
        email: 'ava.moore@example.com',
        address: '707 Cedar Street',
        date_naissance: '1994-07-08',
    },
];

export const service = [
    {   
        id: 1,
        Titre: "Réparation de fuite d'eau",
        Description: "Intervention pour réparer une fuite d'eau",
        Catégorie: "Plomberie",
        Tarif: 50.0,
        Localisation: "Quelque part",
        etat: 'intéresser',
        cin: 'ABC123',
    },
    {
        id: 2,
        Titre: "Installation de prise électrique",
        Description: "Installation d'une nouvelle prise électrique",
        Catégorie: "Électricité",
        Tarif: 60.0,
        Localisation: "Un endroit",
        etat: 'intéresser',
        cin: 'XYZ789',
    },
    {
        id: 3,
        Titre: "Entretien de jardin",
        Description: "Services d'entretien et d'aménagement paysager",
        Catégorie: "Jardinage et Aménagement Paysager",
        Tarif: 40.0,
        Localisation: "Votre jardin",
        etat: 'intéresser',
        cin: 'DEF456', 
    },
    {
        id: 4,
        Titre: "Nettoyage de maison",
        Description: "Nettoyage complet de votre domicile",
        Catégorie: "Nettoyage",
        Tarif: 30.0,
        Localisation: "À domicile",
        etat: 'intéresser',
        cin: 'GHI789', 
    },
    {
        id: 5,
        Titre: "Réparation de lave-vaisselle",
        Description: "Réparation et entretien de lave-vaisselle",
        Catégorie: "Réparation et Entretien d'Appareils Ménagers",
        Tarif: 55.0,
        Localisation: "Où vous en avez besoin",
        etat: 'intéresser',
        cin: 'JKL123',
    },
    {
        id: 6,
        Titre: "Aide au déménagement",
        Description: "Assistance pour le déménagement de vos biens",
        Catégorie: "Déménagement",
        Tarif: 70.0,
        Localisation: "Partout",
        etat: 'intéresser',
        cin: 'MNO456',  
    },
    {
        id: 7,
        Titre: "Assistance informatique",
        Description: "Support informatique et dépannage",
        Catégorie: "Informatique",
        Tarif: 45.0,
        Localisation: "En ligne ou sur site",
        etat: 'intéresser',
        cin: 'PQR789', 
    },
    {
        id: 8,
        Titre: "Menuiserie sur mesure",
        Description: "Services de menuiserie personnalisés",
        Catégorie: "Menuiserie",
        Tarif: 80.0,
        Localisation: "Atelier de menuiserie",
        etat: 'intéresser',
        cin: 'STU123', 
    },
    {
        id: 9,
        Titre: "Peinture intérieure",
        Description: "Peinture des murs intérieurs de votre maison",
        Catégorie: "Peinture",
        Tarif: 65.0,
        Localisation: "Résidence",
        etat: 'intéresser',
        cin: 'VWX456', 
    },
    {
        id: 10,
        Titre: "Coiffure à domicile",
        Description: "Services de coiffure dans le confort de votre maison",
        Catégorie: "Coiffure à Domicile",
        Tarif: 55.0,
        Localisation: "Chez vous",
        etat: 'intéresser',
        cin: 'YZA789',  
    },
    {
        id: 11,
        Titre: "Garde d'animaux",
        Description: "Service de garde et de soins pour vos animaux de compagnie",
        Catégorie: "Garde d'Animaux",
        Tarif: 35.0,
        Localisation: "Chez le propriétaire ou à domicile",
        etat: 'intéresser',
        cin: 'DEF456', 
    },
    {
        id: 12,
        Titre: "Tutorat personnalisé",
        Description: "Soutien scolaire et tutorat pour divers sujets",
        Catégorie: "Tutorat",
        Tarif: 50.0,
        Localisation: "En ligne ou en personne",
        etat: 'intéresser',
        cin: 'ABC123', 
    },
];


export const Titres = [
    'Plomberie',
    'Électricité',
    'Jardinage et Aménagement Paysager',
    "Réparation et Entretien d'Appareils Ménagers",
    "Services de Déménagement",
    "Services Informatiques",
    "Services de Menuiserie",
    "Services de Peinture",
    "Services de Coiffure à Domicile",
    "Services de Garde d'Animaux",
    "Services de Tutorat"
]
export const Catégories = [
    "Plomberie",
    "Électricité",
    "Jardinage et Aménagement Paysager",
    "Nettoyage",
    "Réparation et Entretien d'Appareils Ménagers",
    "Déménagement",
    "Informatique",
    "Menuiserie",
    "Peinture",
    "Coiffure à Domicile",
    "Garde d'Animaux",
    "Tutorat",
]
export const Localisation = [
    "Agadir",
    "Al Hoceima",
    "Assilah",
    "Azemmour",
    "Beni Mellal",
    "Berkane",
    "Berrechid",
    "Casablanca",
    "Chefchaouen",
    "Dakhla",
    "El Hajeb",
    "El Jadida",
    "Errachidia",
    "Essaouira",
    "Fès",
    "Fnideq",
    "Guelmim",
    "Ifrane",
    "Kenitra",
    "Khenifra",
    "Khouribga",
    "Ksar El Kebir",
    "Laâyoune",
    "Larache",
    "Marrakech",
    "Martil",
    "Meknès",
    "Midelt",
    "Mohammedia",
    "Nador",
    "Ouarzazate",
    "Ouezzane",
    "Oujda",
    "Rabat",
    "Safi",
    "Salé",
    "Sefrou",
    "Settat",
    "Sidi Kacem",
    "Tanger",
    "Taza",
    "Témara",
    "Tétouan",
    "Tiznit",

];
